### ISSUE TITLE
Extra verses in SNG1

### ISSUE THREAD

**Issue by LAfricain** [BeTheLight/ENG-B-CPDV2009-pd-PSFM#12]
What the extra verses on SNG1? The Vulgate stop to 16. 16 to 19 are extra, 20-21 correspond to 16.

**Comment by LAfricain** [comment]
What I do not understand is exactly what these verses correspond to? There are not in the vulgate?

**Comment by cmahte** [comment]
This issue diverges to only be of concern in the Crosswire branch. this edition follows Ron's original versification without change. (there is a versification file in the project.)
