### ISSUE TITLE
Restructure this repository

### ISSUE THREAD

**Issue by DavidHaslam** [BeTheLight/ENG-B-CPDV2009-pd-PSFM#14]
Suggest move all the SFM files to a folder named **USFM**.

Likewise several other files could be moved into suitably named folders to reduce clutter.

I always like to see a well-structured repository before I get more involved in a project.

It would be useful to also provide a **README.md** file to give information to first time visitors.

**Comment by LAfricain** [comment]
Currently I'm working on  the fork of this project. But I will push all on my gitlab repo.

**Comment by cmahte** [comment]
done, but the Readme could be better.
